# World-OWID Dataset

# Explenations

In this guthub repository you will find all of the explenations organized
https://github.com/owid/co2-data/blob/master/owid-co2-codebook.csv

In [3]:
import pandas as pd 
explenations = pd.read_csv('DataSets /owid-Explenations.csv')

In [4]:
explenations

,column,description,source
0,country,Geographic location.,Our World in Data
1,year,Year of observation.,Our World in Data
2,iso_code,"ISO 3166-1 alpha-3, three-letter country codes.",International Organization for Standardization
3,population,Population of each country or region.,Our World in Data based on different sources (...
4,gdp,Gross domestic product measured in internation...,Maddison Project Database 2020 (Bolt and van Z...
...,...,...,...
74,temperature_change_from_n2o,Change in global mean surface temperature (in ...,Our World in Data based on Jones et al. (2023)
75,total_ghg,Total greenhouse gas emissions including land-...,Our World in Data based on Climate Analysis In...
76,total_ghg_excluding_lucf,Total greenhouse gas emissions excluding land-...,Our World in Data based on Climate Analysis In...
77,trade_co2,Annual net carbon dioxide (CO₂) emissions embe...,Global Carbon Budget (2022)
78,trade_co2_share,Annual net carbon dioxide (CO₂) emissions embe...,Global Carbon Budget (2022)

# Data

In [3]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Users/wout_vp/venv-metal/lib/python3.11/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/wout_vp/venv-metal/lib/python3.11/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
df = pd.read_excel('DataSets /WORLD-OWID.xlsx')

In [7]:
df

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,co2_including_luc_growth_prct,...,energy_per_gdp,flaring_co2,gas_co2,ghg_per_capita,land_use_change_co2,land_use_change_co2_per_capita,oil_co2,other_industry_co2,primary_energy_consumption,total_ghg
0,1750,7.456645e+08,NaN,NaN,NaN,9.351,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1751,NaN,NaN,NaN,NaN,9.351,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1752,NaN,NaN,NaN,NaN,9.354,0.039,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1753,NaN,NaN,NaN,NaN,9.354,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1754,NaN,NaN,NaN,NaN,9.358,0.039,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,2017,7.599822e+09,1.104307e+14,1507.923,0.198,36096.738,1.612,40428.684,376.644,0.940,...,1.425,391.992,7144.928,6.349,4331.947,0.570,12242.628,302.294,157406.344,48251.879
268,2018,7.683790e+09,1.136302e+14,1569.218,0.204,36826.508,2.022,41007.867,579.183,1.433,...,1.424,412.116,7529.847,6.425,4181.356,0.544,12266.017,302.479,161772.625,49368.039
269,2019,7.764951e+09,NaN,1617.507,0.208,37082.559,0.695,41639.840,631.976,1.541,...,NaN,439.254,7647.528,6.408,4557.283,0.587,12345.653,306.639,163173.953,49758.230
270,2020,7.840953e+09,NaN,1637.537,0.209,35264.086,-4.904,39321.844,-2317.996,-5.567,...,NaN,407.584,7556.290,NaN,4057.758,0.518,11191.809,296.302,156669.938,NaN
271,2021,7.909295e+09,NaN,1672.592,0.211,37123.852,5.274,41062.895,1741.050,4.428,...,NaN,416.526,7921.830,NaN,3939.044,0.498,11837.159,296.146,165319.688,NaN

In [6]:
df.columns

Index(['year', 'population', 'gdp', 'cement_co2', 'cement_co2_per_capita',
       'co2', 'co2_growth_prct', 'co2_including_luc',
       'co2_including_luc_growth_abs', 'co2_including_luc_growth_prct',
       'co2_including_luc_per_capita', 'co2_including_luc_per_gdp',
       'co2_including_luc_per_unit_energy', 'co2_per_capita', 'co2_per_gdp',
       'co2_per_unit_energy', 'coal_co2', 'consumption_co2',
       'consumption_co2_per_gdp', 'cumulative_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'gas_co2', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'oil_co2',
       'other_industry_co2', 'primary_energy_consumption', 'total_ghg'],
      dtype='object')

# Feature Extraction and Engineering

In [8]:
features_to_keep = ['year', 'cement_co2', 'co2', 'coal_co2', 'flaring_co2', 'gas_co2', 'oil_co2']  # Consumption_co2, 

df = df[features_to_keep]

**Reasoning for the chosen features** 

Since we are tryng to predict co2 emissions based on different industries, we can already exclude the population and GDP, because this factors have nothing to do with the industry-related emissions and will have a negative effect on accurately predicting the emissions trough industries. 

For this notebook we will only take features directly related to an Industry, also of every industry we will only take 1 suitable feature to start with. 

For example, 'co2_growth_prct' = Annual percentage growth in total production-based emissions of carbon dioxide (CO₂), since this is the total amount of all production-based emissions together, this will not give us a clearly overview of which of the productions contributed the most to the total amount of co2 emissions. These features are not sector related but rather give us an overall overview, which will not help us. 

Also a reason to not use this the amounts is because our target variable which we are trying to predict will be co2, which is already measured as the amount of total production-based emissions of co2 

Once again, here you can find the explenations: https://github.com/owid/co2-data/blob/master/owid-co2-codebook.csv

In [8]:
# Chekking for missing values 

null_values = df.isnull().sum()

nan_values = df.isna().sum()

print("Null-values:")
print(null_values)

print("\nNaN-values:")
print(nan_values)

Null-values:
year                     0
cement_co2             130
co2                      0
coal_co2                 0
flaring_co2            200
gas_co2                132
land_use_change_co2    100
oil_co2                105
other_industry_co2     154
dtype: int64

NaN-values:
year                     0
cement_co2             130
co2                      0
coal_co2                 0
flaring_co2            200
gas_co2                132
land_use_change_co2    100
oil_co2                105
other_industry_co2     154
dtype: int64

In [9]:
# Replacing our missing values with the mean of that feature 

mean_values = df.mean()

for feature in df.columns:
    df[feature].fillna(mean_values[feature], inplace=True)

print(df)

     year   cement_co2        co2   coal_co2  flaring_co2      gas_co2  \
0    1750   317.372711      9.351      9.351   256.309556  1814.698707
1    1751   317.372711      9.351      9.351   256.309556  1814.698707
2    1752   317.372711      9.354      9.354   256.309556  1814.698707
3    1753   317.372711      9.354      9.354   256.309556  1814.698707
4    1754   317.372711      9.358      9.358   256.309556  1814.698707
..    ...          ...        ...        ...          ...          ...
267  2017  1507.923000  36096.738  14506.974   391.992000  7144.928000
268  2018  1569.218000  36826.508  14746.831   412.116000  7529.847000
269  2019  1617.507000  37082.559  14725.978   439.254000  7647.528000
270  2020  1637.537000  35264.086  14174.564   407.584000  7556.290000
271  2021  1672.592000  37123.852  14979.598   416.526000  7921.830000

     land_use_change_co2       oil_co2  other_industry_co2
0            4316.805465   3625.609168           82.069576
1            4316.805465   3625.609168           82.069576
2            4316.805465   3625.609168           82.069576
3            4316.805465   3625.609168           82.069576
4            4316.805465   3625.609168           82.069576
..                   ...           ...                 ...
267          4331.947000  12242.628000          302.294000
268          4181.356000  12266.017000          302.479000
269          4557.283000  12345.653000          306.639000
270          4057.758000  11191.809000          296.302000
271          3939.044000  11837.159000          296.146000

[272 rows x 9 columns]

/var/folders/3d/ww3w94xd4y9bsnytmzvvs9340000gn/T/ipykernel_26269/2831490286.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature].fillna(mean_values[feature], inplace=True)

In [10]:
# Chekking for missing values to see if we correctl replced them 

null_values = df.isnull().sum()

nan_values = df.isna().sum()

print("Null-values:")
print(null_values)

print("\nNaN-values:")
print(nan_values)

Null-values:
year                   0
cement_co2             0
co2                    0
coal_co2               0
flaring_co2            0
gas_co2                0
land_use_change_co2    0
oil_co2                0
other_industry_co2     0
dtype: int64

NaN-values:
year                   0
cement_co2             0
co2                    0
coal_co2               0
flaring_co2            0
gas_co2                0
land_use_change_co2    0
oil_co2                0
other_industry_co2     0
dtype: int64

# Defining our X and y

In [9]:
# Making our 'year' our index 

df.set_index('year', inplace=True)

In [10]:
df.to_csv('WORLD-OWID-Features-NO_EDA')

In [12]:
#X = df.drop('co2', axis=1)
#y = df['co2']

In [13]:
#y